Repository TinyCommunity/tinycolor2, pull requests merged in 2021-07, with the labels that each got.

#4 Update underlying color with setting alpha and opacity, and re-structure as library.
  lib/src/color_extension.dart
  lib/src/conversion.dart
  lib/src/hsl_color.dart
  lib/src/tinycolor.dart
  lib/src/util.dart
  lib/tinycolor2.dart
  test/tinycolor_test.dart
  test/util_test.dart
Labels: bug

#14 Replace .gitignore
  .gitignore
  pubspec.lock
Labels: enhancement

#16 Add .equals()
  lib/src/tinycolor.dart
Labels: enhancement

#17 Add .toHex8()
  lib/src/tinycolor.dart
Labels: enhancement

#24 Upgrade to null safety
  lib/src/conversion.dart
  lib/src/hsl_color.dart
  lib/src/tinycolor.dart
  pubspec.yaml
Labels: enhancement

#28 Added linting
  analysis_options.yaml
  example/lib/main.dart
  example/pubspec.lock
  lib/src/color_extension.dart
  lib/src/conversion.dart
  lib/src/hsl_color.dart
  lib/src/tinycolor.dart
  lib/src/util.dart
  pubspec.yaml
Labels: enhancement

#31 Fix readme for tiny changes
  README.md
Labels: documentation

#32 Rename LICENSE to LICENSE.md and updates
  LICENSE.md
Labels: enhancement

#30 Adding Github Actions for CI/CD
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: enhancement
